# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028f8444034b5c9133c99ddb69e5ae121ad4121e84b6eeae0f85c62b8ff2df6a525727fd5ca6088fdd7876d9f67212a27962faa1c3cfee246fb885e65508699e

test:
  secret_key_base: c07341cc47dcce5d3eb87f509d57d3777f43b9426e791e6c703bc774f9c080b7eb2ecf556fd54bc3f4918c697e5cb741f0f144b7e42cc93065cdf471a764f9d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
